# Generated by Django 2.2.7 on 2019-11-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ecode',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
