# Generated by Django 2.2.7 on 2019-12-07 11:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ehandler', '0002_auto_20191207_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eenddate',
            field=models.DateField(default=datetime.datetime(2019, 12, 7, 11, 4, 13, 48761, tzinfo=utc), verbose_name='Event End date'),
        ),
    ]
