# Generated by Django 2.2.7 on 2019-12-07 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ehandler', '0003_auto_20191207_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='edate',
            field=models.DateTimeField(verbose_name='Event Start date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eenddate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 11, 7, 57, 97411, tzinfo=utc), verbose_name='Event End date'),
        ),
    ]
