# Generated by Django 2.2.7 on 2019-12-06 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ehandler', '0004_event_eattendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ehelpers',
            field=models.ManyToManyField(related_name='helpers', to=settings.AUTH_USER_MODEL),
        ),
    ]
