# Generated by Django 2.2.7 on 2019-12-07 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehandler', '0004_auto_20191207_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eattendees',
            field=models.ManyToManyField(null=True, related_name='attendees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='eenddate',
            field=models.DateTimeField(verbose_name='Event End date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ehelpers',
            field=models.ManyToManyField(null=True, related_name='helpers', to=settings.AUTH_USER_MODEL),
        ),
    ]
